select A.CUSTOMERID,A.CUSTOMERNAME,A.COUNTRY,A.SEGMENT,
B.ORDERID,B.ORDERDATE,B.SHIPDATE,B.SHIPMODE,
C.PRODUCTID,C.CATEGORY,C.PRODUCTNAME,B.ORDERSELLINGPRICE-B.ordercostprice AS PROFIT
FROM {{ ref('Source_customer') }} as A 
INNER JOIN {{ ref('Source_orders') }} as B 
on A.CUSTOMERID = B.CUSTOMERID
INNER JOIN {{ ref('Source_product') }} AS C
ON B.PRODUCTID=C.PRODUCTID